site_name: Vanilla Classic Wiki
site_url: https://MitsukiWeb.github.io/VanillaClassicWiki/
site_description: Wiki oficial de Vanilla Classic RO - Ep 7 Servidor Ancient.
site_author: Mitsuki

theme:
  name: material
  logo: images/logo.png         # <--- Aquí apunta a docs/images/logo.png
  favicon: images/logo.png      # <--- Icono en la pestaña del navegador
  language: es
  palette:
    # Modo Oscuro por defecto (Ideal para gamers)
    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
    - scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight

nav:
  - Inicio: index.md
  - Información:
      - 'Rates y Episodio': info/rates.md
      - 'Comandos': info/comandos.md
  - Sistemas:
      - 'Eventos': sistemas/eventos.md
  - Descargas: descargas.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  plugins:
  - search
  - i18n:
      docs_structure: suffix # Usaremos la extensión .en.md para inglés
      languages:
        - locale: es
          default: true
          name: Español
          build: true
        - locale: en
          name: English
          build: true
